---
- name: Our first playbook
  hosts: darko
  gather_facts: false

  tasks:
          - name: Copying file from A to B
            copy:
                    src: startingoff.conf
                    dest: /tmp/startingoff_moved.conf
                    backup: yes
                    force: yes

