---
- name: Learning about vault
  hosts: futurama

  vars_files:
    - vars/creds.yaml

  tasks:
    - name: Print out values within creds.yaml
      debug:
        var: ansible_ssh_pass

    - name: Print out more values within creds.yaml
      debug:
        var: vzw_user
